services:
  postgres-db:
    container_name: flask_blog_postgres_container
    # uts: host
    image: postgres:bookworm
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test_123
      POSTGRES_DB: miniblog
    ports:
      - 5432:5432

