"""increase password size

Revision ID: 185c6dd2699b
Revises: 74bacd668923
Create Date: 2025-04-22 12:19:13.847061

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "185c6dd2699b"
down_revision = "74bacd668923"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("blog_user", schema=None) as batch_op:
        batch_op.alter_column(
            "password",
            existing_type=sa.VARCHAR(length=128),
            type_=sa.String(length=256),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("blog_user", schema=None) as batch_op:
        batch_op.alter_column(
            "password",
            existing_type=sa.String(length=256),
            type_=sa.VARCHAR(length=128),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
